# Based on the work of Emily Gorcenski
# https://www.emilygorcenski.com/post/configuring-a-data-science-workbench

version: "3.8"

services:
  db:
    restart: always
    image: postgres:12.10
    expose:
      - "${PG_PORT}"
    ports:
      - "${PG_PORT}:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data/

  s3:
    platform: linux/x86_64 # Remove this line if you are not using Docker Desktop on Apple Silicon
    image: minio/minio:RELEASE.2024-06-29T01-20-47Z.fips
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_UI_PORT}:9001" 
    networks:
      - frontend
      - backend
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  create_buckets:
    platform: linux/x86_64 # Remove this line if you are not using Docker Desktop on Apple Silicon
    image: minio/mc:RELEASE.2024-06-24T19-40-33Z.fips
    depends_on:
      - s3
    networks:
      - backend
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      /usr/bin/mc config host add s3 http://s3:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_ACCESS_KEY} --api S3v4;
      /usr/bin/mc mb --ignore-existing s3/${MLFLOW_BUCKET_NAME};
      /usr/bin/mc anonymous set download s3/${MLFLOW_BUCKET_NAME};
      /usr/bin/mc anonymous set upload s3/${MLFLOW_BUCKET_NAME};
      /usr/bin/mc anonymous set public s3/${MLFLOW_BUCKET_NAME};
      exit 0;
      '

  tracking_server:
    depends_on:
      - db
    restart: always
    image: bitnami/mlflow:2.14.1
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      - frontend
      - backend
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:${MINIO_PORT}
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      mlflow server \
        --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@db:${PG_PORT}/${PG_DATABASE} \
        --host 0.0.0.0 \
        --port 5000 \
        --artifacts-destination s3://mlflow/;
      '

volumes:
  db_data:
  minio_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge